### ISSUE TITLE
SW: Install ORFEO toolbox

### ISSUE THREAD

**Issue by felixcremer** [SAR-EDU/sarbian#7]
Install the orfeo toolbox.
It should be cleared if the otb package in the debian repository is good enough.
We need the mosaic module.
https://www.orfeo-toolbox.org/download/

The command otbcli_Mosaic is needed.

**Comment by vpoughon** [comment]
Hi, I'm a developer on orfeo toolbox. Feel free to let us know, or open an issue on our gitlab (https://gitlab.orfeo-toolbox.org/orfeotoolbox/otb) if you need help from our side.
